[metadata.heroku]
  root-package = "arso"
  install = [ "./..." ]
  go-version = "go1.10.1"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.2.1"

[[constraint]]
  name = "github.com/go-chi/docgen"
  version = "1.0.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[prune]
  go-tests = true
  unused-packages = true
